package Vista;

import Controlador.ControladorFerreteria;
import Modelo.Cliente;
import Modelo.DetalleVenta;
import Modelo.Producto;
import Modelo.Venta;
import java.util.ArrayList;

public class PantallaIngresaVenta extends javax.swing.JFrame {

    public PantallaIngresaVenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BotonAgregarNewVenta = new javax.swing.JButton();
        BotonGuardarVenta = new javax.swing.JButton();
        LeerRutVenta = new javax.swing.JTextField();
        LeerCodVenta = new javax.swing.JTextField();
        LeerFechaVenta = new javax.swing.JTextField();
        LeerCodProdVenta = new javax.swing.JTextField();
        LeerCantVenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("INGRESANDO VENTA");

        jLabel7.setText("Agregar nuevo producto:");

        BotonAgregarNewVenta.setText("Si/Agregar");
        BotonAgregarNewVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarNewVentaActionPerformed(evt);
            }
        });

        BotonGuardarVenta.setText("No/Guardar");
        BotonGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarVentaActionPerformed(evt);
            }
        });

        LeerRutVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerRutVentaActionPerformed(evt);
            }
        });

        LeerCodVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerCodVentaActionPerformed(evt);
            }
        });

        LeerFechaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerFechaVentaActionPerformed(evt);
            }
        });

        LeerCodProdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerCodProdVentaActionPerformed(evt);
            }
        });

        LeerCantVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeerCantVentaActionPerformed(evt);
            }
        });

        jLabel3.setText("Ingrese el Rut del cliente:");

        jLabel4.setText("Código de la venta:");

        jLabel10.setText("Fecha de la venta:");

        jLabel11.setText("Código del producto:");

        jLabel12.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(LeerRutVenta)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(BotonAgregarNewVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                                                                .addComponent(BotonGuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(LeerCodVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(LeerFechaVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(LeerCodProdVenta)
                                                        .addComponent(LeerCantVenta))
                                                .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LeerRutVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LeerCodVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LeerFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LeerCodProdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LeerCantVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(BotonAgregarNewVenta)
                                        .addComponent(BotonGuardarVenta))
                                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LeerRutVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerRutVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeerRutVentaActionPerformed

    private void LeerCodVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerCodVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeerCodVentaActionPerformed

    private void LeerFechaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerFechaVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeerFechaVentaActionPerformed

    private void LeerCodProdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerCodProdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeerCodProdVentaActionPerformed

    private void LeerCantVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeerCantVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LeerCantVentaActionPerformed

    private void BotonAgregarNewVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarNewVentaActionPerformed
        // TODO add your handling code here:
        new PantallaNewProdVenta().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonAgregarNewVentaActionPerformed

    private void BotonGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarVentaActionPerformed
        // TODO add your handling code here:

        ArrayList <DetalleVenta> detallesVenta = new ArrayList();

        String rut = LeerRutVenta.getText();
        String codigoVentaString = LeerCodVenta.getText();
        String fecha = LeerFechaVenta.getText();
        String cantString = LeerCantVenta.getText();

        int codVenta = Integer.parseInt(codigoVentaString);
        int cantidad = Integer.parseInt(cantString);

        Cliente cliente = ControladorFerreteria.getInstance().buscarCliente(rut);
        Producto producto = ControladorFerreteria.getInstance().buscarProducto(codVenta);

        DetalleVenta detalle = new DetalleVenta(cantidad, producto);
        detallesVenta.add(detalle);
        Venta venta = new Venta(codVenta,cliente, fecha, detallesVenta);

        ControladorFerreteria.getInstance().creaVenta(venta);

        new PantallaMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotonGuardarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarNewVenta;
    private javax.swing.JButton BotonGuardarVenta;
    private javax.swing.JTextField LeerCantVenta;
    private javax.swing.JTextField LeerCodProdVenta;
    private javax.swing.JTextField LeerCodVenta;
    private javax.swing.JTextField LeerFechaVenta;
    private javax.swing.JTextField LeerRutVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
